"""
CRE-DTS worked adoption demonstration on SYNTHETIC data.

Walks through the four adoption steps in Technical Design Specification v1.10, Section 12.3:
  1. Map an institution's own loan tape to the data dictionary (Appendix A)
  2. Validate against the institution's own loan history (out-of-time backtest, Section 7)
  3. Calibrate watch-level thresholds to the institution's false-alarm tolerance (Framework Section 3)
  4. Integrate the signals into a watchlist with reason codes and response actions

Every loan, number and field name here is generated by this script. "Institution X" is fictional.
Nothing here is evidence of accuracy on real loans or of deployment at any institution.
Prepared September 2026, after the petition was filed.
"""
import json
import numpy as np
import pandas as pd
import xgboost as xgb
from sklearn.isotonic import IsotonicRegression
from sklearn.metrics import roc_auc_score, brier_score_loss

SEED = 2026
rng = np.random.default_rng(SEED)

# ------------------------------------------------------------------ synthetic world
QUARTERS = pd.period_range("2013Q1", "2024Q4", freq="Q")
NQ = len(QUARTERS)
qi = {q: i for i, q in enumerate(QUARTERS)}

# 10-year Treasury path (stylized): low 2013-2021, sharp rise 2022-2023
ust10 = np.interp(np.arange(NQ), [0, 12, 28, 36, 40, 44, 47],
                  [0.020, 0.023, 0.015, 0.016, 0.035, 0.043, 0.042])
TYPES = ["Office", "Multifamily", "Retail", "Industrial"]
SPREAD = {"Office": 0.022, "Multifamily": 0.017, "Retail": 0.023, "Industrial": 0.019}
CAP0 = {"Office": 0.065, "Multifamily": 0.055, "Retail": 0.068, "Industrial": 0.060}
LIMITS = {  # institution-set underwriting limits (CFG): dscr_min, ltv_max, dy_min
    "Office": (1.35, 0.60, 0.10), "Multifamily": (1.25, 0.70, 0.08),
    "Retail": (1.35, 0.65, 0.095), "Industrial": (1.30, 0.65, 0.09)}


def type_trend(ptype, i):
    """Quarterly NOI drift by property type; office weakens after 2020."""
    if ptype == "Office":
        return 0.004 if i < 29 else -0.018
    if ptype == "Retail":
        return -0.002 if i < 28 else 0.001
    return 0.006


def debt_constant(r, years=30):
    m = r / 12
    return 12 * m / (1 - (1 + m) ** (-12 * years))


N_LOANS = 3000
rows = []
for loan in range(N_LOANS):
    ptype = rng.choice(TYPES, p=[0.3, 0.3, 0.2, 0.2])
    o = int(rng.integers(0, 40))                     # origination quarter index (2013Q1-2022Q4)
    term_q = int(rng.choice([12, 20, 28, 40]))        # 3, 5, 7, 10 years
    mat = o + term_q
    io = rng.random() < 0.55
    val0 = float(np.exp(rng.normal(np.log(8e6), 0.7)))
    ltv0 = float(rng.uniform(0.50, 0.78))
    bal0 = val0 * ltv0
    cap_o = CAP0[ptype] + rng.normal(0, 0.004)
    noi = val0 * cap_o
    coupon = ust10[o] + SPREAD[ptype] + rng.normal(0, 0.003)
    ds = bal0 * (coupon if io else debt_constant(coupon))
    occ = float(np.clip(rng.normal(0.93, 0.04), 0.7, 1.0))
    sponsor_shock = rng.normal(0, 0.006)              # loan-specific drift
    bal = bal0
    hist_noi, hist_occ, hist_dscr = [], [], []
    for i in range(o, min(mat + 1, NQ)):
        if i > o:
            g = type_trend(ptype, i) + sponsor_shock + rng.normal(0, 0.02)
            noi *= np.exp(g)
            occ = float(np.clip(occ + 0.6 * g + rng.normal(0, 0.006), 0.35, 1.0))
            if not io:
                bal *= 0.995
        cap_t = CAP0[ptype] + 0.55 * (ust10[i] - ust10[0]) + (0.008 if (ptype == "Office" and i >= 30) else 0)
        value = noi / cap_t
        dscr = noi / ds
        hist_noi.append(noi); hist_occ.append(occ); hist_dscr.append(dscr)
        mtm = (mat - i) * 3
        # refinance gap (Spec 4.3): supportable loan vs balloon balance
        dmin, lmax, dymin = LIMITS[ptype]
        refi_rate = ust10[i] + SPREAD[ptype]
        L = min(noi / (dmin * debt_constant(refi_rate)), lmax * noi / cap_t, noi / dymin)
        gap = max(0.0, bal - L) / bal
        rows.append(dict(loan=loan, q=i, ptype=ptype, orig_q=o, mat_q=mat, balance=bal, coupon=coupon,
                         noi=noi, value=value, occ=occ, debt_service=ds, mtm=mtm, refi_gap=gap,
                         noi_4q=hist_noi[-5] if len(hist_noi) >= 5 else np.nan,
                         occ_4q=hist_occ[-5] if len(hist_occ) >= 5 else np.nan,
                         dscr_4q=hist_dscr[-5] if len(hist_dscr) >= 5 else np.nan))
        # event process
        noi_chg = (noi / hist_noi[-5] - 1) if len(hist_noi) >= 5 else 0.0
        logit = (-6.2 + 2.2 * max(0, 1.15 - dscr) + 2.5 * max(0, bal / value - 0.75)
                 - 3.0 * min(noi_chg, 0.1) + 1.2 * gap)
        p_term = 1 / (1 + np.exp(-logit))
        if i == mat:  # maturity: refinance or maturity default
            p_mat = 1 / (1 + np.exp(-(-3.2 + 9.0 * gap)))
            rows[-1]["event"] = "maturity_default" if rng.random() < p_mat else "payoff"
            break
        if rng.random() < p_term:
            rows[-1]["event"] = "term_default"
            break
panel = pd.DataFrame(rows)
panel["event"] = panel["event"].fillna("")

# ------------------------------------------------------------------ STEP 1: institution tape + mapping
# Institution X reports quarterly; financials for quarter t become available 45 days after quarter end.
qend = {i: q.end_time.normalize() for i, q in enumerate(QUARTERS)}
tape = pd.DataFrame({
    "Loan_Num": "IX-" + panel["loan"].astype(str).str.zfill(5),
    "Prop_Type_Cd": panel["ptype"].map({"Office": "OF", "Multifamily": "MF", "Retail": "RT", "Industrial": "IN"}),
    "Rpt_Period_End": panel["q"].map(qend),
    "Rpt_Recv_Dt": panel["q"].map(qend) + pd.Timedelta(days=45),
    "Curr_Bal": panel["balance"].round(0),
    "Note_Rate_Pct": (panel["coupon"] * 100).round(3),
    "Net_Op_Inc_TTM": panel["noi"].round(0),
    "Ann_Debt_Svc": panel["debt_service"].round(0),
    "Appraised_Val": panel["value"].round(0),
    "Phys_Occ_Pct": (panel["occ"] * 100).round(1),
    "Mat_Dt": panel["mat_q"].map(lambda i: (QUARTERS[0] + i).end_time.normalize()),
})
MAPPING = [
    ("Loan_Num", "loan_id", "Renamed"),
    ("Prop_Type_Cd", "property_type", "Code list OF/MF/RT/IN mapped to Office/Multifamily/Retail/Industrial"),
    ("Rpt_Period_End", "reporting_period_end", "Renamed"),
    ("Rpt_Recv_Dt", "available_date", "Renamed; used for the point-in-time join (App. A.1)"),
    ("Curr_Bal", "balance", "Renamed"),
    ("Note_Rate_Pct", "coupon", "Percent to decimal (÷100)"),
    ("Net_Op_Inc_TTM", "noi", "Renamed"),
    ("Ann_Debt_Svc", "debt_service", "Renamed"),
    ("Appraised_Val", "value_current", "Renamed"),
    ("Phys_Occ_Pct", "occupancy", "Percent to decimal (÷100)"),
    ("Mat_Dt", "maturity_date", "Renamed; months_to_maturity derived"),
]
NOT_HELD = ["watchlist_flag", "borrower_strength"]
m = {src: dst for src, dst, _ in MAPPING}
mapped = tape.rename(columns=m)
mapped["coupon"] /= 100
mapped["occupancy"] /= 100
mapped["property_type"] = mapped["property_type"].map({"OF": "Office", "MF": "Multifamily", "RT": "Retail", "IN": "Industrial"})
# point-in-time: an observation at quarter-end t can only use a report available by t, i.e. the prior quarter's report
panel["obs_q"] = panel["q"] + 1
obs_date = panel["obs_q"].map(lambda i: (QUARTERS[0] + i).end_time.normalize())
assert (mapped["available_date"].values <= obs_date.values).all()

# derived features (App. A.4)
df = panel.copy()
df["ltv_current"] = df["balance"] / df["value"]
df["dscr"] = df["noi"] / df["debt_service"]
df["debt_yield"] = df["noi"] / df["balance"]
df["noi_chg_4q"] = df["noi"] / df["noi_4q"] - 1
df["occ_chg_4q"] = df["occ"] - df["occ_4q"]
df["dscr_chg_4q"] = df["dscr"] - df["dscr_4q"]
df["mtm_obs"] = df["mtm"] - 3
df["rate_chg_since_orig"] = [ust10[q] - ust10[o] for q, o in zip(df["q"], df["orig_q"])]
for t in TYPES:
    df["pt_" + t] = (df["ptype"] == t).astype(int)

# 12-month label measured from the observation quarter: default reported in obs_q .. obs_q+3
ev = panel[panel["event"].str.contains("default")][["loan", "q", "event"]].rename(columns={"q": "def_q", "event": "def_type"})
df = df.merge(ev, on="loan", how="left")
df["y_12m"] = ((df["def_q"] >= df["obs_q"] - 1) & (df["def_q"] <= df["obs_q"] + 2)).astype(int)
df = df[df["event"] == ""]  # the quarter a loan exits is not an observation
FEATS = ["ltv_current", "dscr", "debt_yield", "occ", "refi_gap", "mtm_obs", "noi_chg_4q",
         "occ_chg_4q", "dscr_chg_4q", "rate_chg_since_orig"] + ["pt_" + t for t in TYPES]
MONO = {"ltv_current": 1, "refi_gap": 1, "dscr": -1, "debt_yield": -1, "occ": -1}

obs_period = df["obs_q"].map(lambda i: QUARTERS[0] + i if i < NQ else QUARTERS[-1] + (i - NQ + 1))
df["obs_year"] = [p.year for p in obs_period]

# ------------------------------------------------------------------ STEP 2: historical validation (out-of-time)
train = df[(df["obs_year"] >= 2014) & (df["obs_year"] <= 2018)]
calib = df[(df["obs_year"] >= 2019) & (df["obs_year"] <= 2020)]
test = df[(df["obs_year"] >= 2022) & (df["obs_year"] <= 2023)]          # 2021 skipped as purge window
current = df[(df["q"] == NQ - 1)]                                       # book as of 2024Q4 report

model = xgb.XGBClassifier(n_estimators=300, max_depth=3, learning_rate=0.05, subsample=0.8,
                          colsample_bytree=0.8, min_child_weight=5, random_state=SEED,
                          monotone_constraints=tuple(MONO.get(f, 0) for f in FEATS),
                          scale_pos_weight=float((train.y_12m == 0).sum() / max(1, (train.y_12m == 1).sum())))
model.fit(train[FEATS], train["y_12m"])
iso = IsotonicRegression(out_of_bounds="clip").fit(model.predict_proba(calib[FEATS])[:, 1], calib["y_12m"])
pd_of = lambda X: iso.predict(model.predict_proba(X[FEATS])[:, 1])
calib = calib.assign(pd=pd_of(calib)); test = test.assign(pd=pd_of(test)); current = current.assign(pd=pd_of(current))

rule = lambda d: ((d["dscr"] < 1.0) | (d["ltv_current"] > 0.80)).astype(int)
auc_model = roc_auc_score(test.y_12m, test.pd)
brier = brier_score_loss(test.y_12m, test.pd)
k = int(0.10 * len(test))
top = test.nlargest(k, "pd")
capture_model = top.y_12m.sum() / test.y_12m.sum()
rule_flag = rule(test)
capture_rule = test.loc[rule_flag == 1, "y_12m"].sum() / test.y_12m.sum()
rule_rate = rule_flag.mean()
# model capture at the rule's flag rate, for a like-for-like comparison
k_rule = int(rule_rate * len(test))
capture_model_at_rule = test.nlargest(k_rule, "pd").y_12m.sum() / test.y_12m.sum()

# ------------------------------------------------------------------ STEP 3: calibrate watch-level thresholds
TOL = {"Watch": 0.15, "Elevated": 0.07, "High": 0.03}   # institution's tolerated share of non-defaulting loan-quarters flagged at or above each level
neg = calib.loc[calib.y_12m == 0, "pd"]
TH = {lvl: float(np.quantile(neg, 1 - r)) for lvl, r in TOL.items()}


def level(p):
    return np.where(p >= TH["High"], "High", np.where(p >= TH["Elevated"], "Elevated",
                    np.where(p >= TH["Watch"], "Watch", "Standard")))


test["level"] = level(test["pd"])
fa = {lvl: float((test.loc[test.y_12m == 0, "pd"] >= TH[lvl]).mean()) for lvl in TH}
hit = {lvl: float((test.loc[test.y_12m == 1, "pd"] >= TH[lvl]).mean()) for lvl in TH}

# early-warning lead time (Spec 7.1): loans defaulting 2022Q2-2024Q4, first Elevated-or-higher flag in the test window before default
lt = []
tq0 = qi[pd.Period("2022Q1")]
for loan, g in df[df["def_q"].notna()].groupby("loan"):
    dq = int(g["def_q"].iloc[0])
    if dq < tq0 + 1 or dq >= NQ:
        continue
    g = g[(g["obs_q"] >= tq0) & (g["obs_q"] <= dq)].assign(pd=lambda d: pd_of(d))
    flagged = g[g["pd"] >= TH["Elevated"]]
    lead = (dq + 1 - int(flagged["obs_q"].min())) * 3 if len(flagged) else None
    lt.append(dict(loan=loan, def_type=g["def_type"].iloc[0] if len(g) else "", lead_m=lead))
lt = pd.DataFrame(lt)
lead_summary = {}
for name, sub in [("All defaults", lt), ("Maturity defaults", lt[lt.def_type == "maturity_default"]),
                  ("Term defaults", lt[lt.def_type == "term_default"])]:
    n = len(sub)
    lead_summary[name] = dict(n=n,
                              flagged=float(sub.lead_m.notna().mean()) if n else 0,
                              ge6=float((sub.lead_m >= 6).mean()) if n else 0,
                              ge12=float((sub.lead_m >= 12).mean()) if n else 0,
                              median=float(sub.lead_m.median()) if sub.lead_m.notna().any() else None)

# ------------------------------------------------------------------ STEP 4: watchlist for the current book
current["level"] = level(current["pd"])
booster = model.get_booster()
contrib = booster.predict(xgb.DMatrix(current[FEATS]), pred_contribs=True)[:, :-1]
REASON = {
    "refi_gap": lambda r: f"Refinance gap {r.refi_gap:.0%}: balloon not refinanceable on current terms",
    "mtm_obs": lambda r: (f"Maturity in {int(r.mtm_obs)} months" if r.mtm_obs > 0 else "At maturity"),
    "ltv_current": lambda r: f"Current LTV {r.ltv_current:.0%}",
    "dscr": lambda r: f"DSCR {r.dscr:.2f}x",
    "noi_chg_4q": lambda r: f"NOI {r.noi_chg_4q:+.0%} over 4 quarters",
    "occ": lambda r: f"Occupancy {r.occ:.0%}",
    "occ_chg_4q": lambda r: f"Occupancy {r.occ_chg_4q*100:+.1f} pts over 4 quarters",
    "dscr_chg_4q": lambda r: f"DSCR {r.dscr_chg_4q:+.2f}x over 4 quarters",
    "debt_yield": lambda r: f"Debt yield {r.debt_yield:.1%}",
    "rate_chg_since_orig": lambda r: f"Rates {r.rate_chg_since_orig*100:+.1f} pts since origination",
}
ACTION = {  # Framework v1.5, Section 3 (illustrative response actions)
    "High": "Workout and restructuring analysis; extension negotiation; recapitalization; loan sale or risk transfer; loss-reserve review",
    "Elevated": "Stressed PD under supervisory scenarios; borrower engagement on a refinancing plan; extension and maturity planning; reserve and liquidity assessment",
    "Watch": "More frequent monitoring; request updated rent roll and operating statements; refresh valuation inputs",
    "Standard": "Routine data refresh and scoring",
}
reasons = []
for idx in range(len(current)):
    c = contrib[idx]
    if current.iloc[idx]["level"] not in ("High", "Elevated"):   # reason codes only for Elevated and High (Spec App. C.4)
        reasons.append("—"); continue
    r = current.iloc[idx]
    adverse = {"dscr": r.dscr < 1.25, "occ": r.occ < 0.90, "ltv_current": r.ltv_current > 0.75,
               "debt_yield": r.debt_yield < 0.09, "refi_gap": r.refi_gap > 0}
    order = [j for j in np.argsort(-c) if c[j] > 0 and FEATS[j] in REASON and adverse.get(FEATS[j], True)][:3]
    reasons.append("; ".join(REASON[FEATS[j]](current.iloc[idx]) for j in order))
current["reasons"] = reasons
current["loan_id"] = "IX-" + current["loan"].astype(str).str.zfill(5)
counts = current["level"].value_counts().reindex(["High", "Elevated", "Watch", "Standard"]).fillna(0).astype(int).to_dict()
sample = pd.concat([current[current.level == "High"].nlargest(3, "pd"),
                    current[current.level == "Elevated"].nlargest(2, "pd"),
                    current[current.level == "Watch"].nlargest(1, "pd"),
                    current[current.level == "Standard"].nsmallest(1, "pd")])

out = dict(
    seed=SEED, n_loans=N_LOANS, n_loan_quarters=int(len(df)),
    split=dict(train="2014-2018", calibration="2019-2020", purge="2021", test="2022-2023",
               n_train=int(len(train)), n_calib=int(len(calib)), n_test=int(len(test)),
               test_default_rate=float(test.y_12m.mean())),
    mapping=[dict(source=s, target=t, transform=x) for s, t, x in MAPPING], not_held=NOT_HELD,
    tape_sample=tape.head(3).astype(str).to_dict(orient="records"),
    validation=dict(auc=auc_model, brier=brier, capture_top10=capture_model,
                    rule_flag_rate=float(rule_rate), capture_rule=float(capture_rule),
                    capture_model_at_rule_rate=float(capture_model_at_rule)),
    thresholds=TH, tolerance=TOL, false_alarm_test=fa, hit_rate_test=hit, lead_time=lead_summary,
    watchlist_counts=counts, n_current=int(len(current)),
    watchlist_sample=[dict(loan_id=r.loan_id, type=r.ptype, pd=float(r.pd), level=r.level,
                           mtm=int(max(r.mtm_obs, 0)), refi_gap=float(r.refi_gap), dscr=float(r.dscr),
                           ltv=float(r.ltv_current), reasons=r.reasons, action=ACTION[r.level])
                      for r in sample.itertuples()],
)
from pathlib import Path
_out = Path(__file__).resolve().parent / "out"
_out.mkdir(exist_ok=True)
json.dump(out, open(_out / "adoption_demo_results.json", "w"), indent=2, default=str)
print(json.dumps({k: out[k] for k in ["split", "validation", "thresholds", "false_alarm_test", "hit_rate_test", "lead_time", "watchlist_counts"]}, indent=2))
