"""
CRE-DTS illustrative outputs on SYNTHETIC data (Technical Design Specification, Appendix C).

Shows the FORMAT of the outputs CRE-DTS produces - 12-month PD, PD term structure, survival curves, risk bands and
reason codes - using the implemented code in src/cre_dts. Every loan and number is generated by this script with a
fixed seed. Nothing here is evidence of predictive accuracy on real loans.

Run:  python examples/illustrative_outputs.py
Writes examples/out/illustrative_outputs.json and examples/out/survival_curves.png
"""
from __future__ import annotations

import os

# PyTorch and XGBoost each ship an OpenMP runtime; on macOS, using both with several threads can crash or hang.
# One thread is plenty for this synthetic example and keeps results identical across machines.
os.environ.setdefault("OMP_NUM_THREADS", "1")

import json
from pathlib import Path

import numpy as np
import pandas as pd

from cre_dts.config import load_underwriting
from cre_dts.explain.reason_codes import top_reasons
from cre_dts.features.refi_gap import add_refi_gap
from cre_dts.models.calibration import IsotonicCalibrator
from cre_dts.models.track_a_xgb import fit_track_a, predict_raw
from cre_dts.models.track_c_surv import (breslow_baseline, concordance_index, fit_deepsurv, log_risk,
                                         survival_curve)

SEED = 11
N_LOANS = 6000
N_CAL = 1500              # held-out calibration set for Track A (Section 6)
HORIZON_Q = 20            # 5-year window, quarters
UST10 = 0.0425            # 10-year Treasury used for current refinance terms
OUT = Path(__file__).resolve().parent / "out"
TYPES = ["office", "multifamily", "retail", "industrial"]
CAP = {"office": 0.080, "multifamily": 0.060, "retail": 0.075, "industrial": 0.065}
FEATURES = ["ltv_current", "dscr", "debt_yield", "occupancy", "refi_gap", "months_to_maturity",
            "noi_chg_4q"]
HIGH, ELEVATED = 0.10, 0.03   # illustrative band cut-offs; each institution sets its own (Section 12.3)


def synthetic_book(rng: np.random.Generator, cfg: dict) -> pd.DataFrame:
    """Loan-level snapshot with a KNOWN built-in default process (for illustration only)."""
    n = N_LOANS
    ptype = rng.choice(TYPES, n, p=[0.30, 0.30, 0.20, 0.20])
    cap = np.array([CAP[p] for p in ptype]) + rng.normal(0, 0.004, n)
    trend = np.where(ptype == "office", -0.05, 0.01)
    noi_chg = rng.normal(trend, 0.08, n)
    value0 = np.exp(rng.normal(np.log(15e6), 0.6, n))
    ltv0 = rng.uniform(0.50, 0.75, n)
    balance = value0 * ltv0
    coupon = rng.uniform(0.035, 0.060, n)
    io = rng.random(n) < 0.6
    noi = value0 * cap * (1 + noi_chg)
    cap_now = cap + 0.006 + np.where(ptype == "office", 0.008, 0.0)
    value = noi / cap_now
    months = rng.integers(3, 85, n)
    debt_service = np.where(io, balance * coupon,
                            balance * 12 * (coupon / 12) / (1 - (1 + coupon / 12) ** -360))
    book = pd.DataFrame({
        "property_type": ptype, "noi": noi, "cap_rate": cap_now, "balance": balance, "coupon": coupon,
        "months_to_maturity": months, "amort_years": np.where(io, 0, 30),
    })
    book = add_refi_gap(book, ust10=UST10, cfg=cfg)
    book["ltv_current"] = balance / value
    book["dscr"] = noi / debt_service
    book["debt_yield"] = noi / balance
    book["occupancy"] = np.clip(rng.normal(0.90, 0.05, n) + 0.6 * noi_chg, 0.4, 1.0)
    book["noi_chg_4q"] = noi_chg
    book["rate_chg_since_orig"] = UST10 - rng.uniform(0.015, 0.045, n)

    # Built-in hazard: term default driven by LTV, DSCR and NOI trend. At maturity the chance of failing to
    # refinance rises with the refinance gap (maturity default); a loan that survives maturity is extended rather
    # than repaid and keeps an elevated hazard that also rises with the gap. Prepayment (about 2% a quarter) and the end of the 5-year window are censoring events.
    mat_q = np.ceil(months / 3).astype(int)
    base = (-6.2 + 3.0 * np.maximum(0.0, book["ltv_current"].to_numpy() - 0.70)
            + 2.0 * np.maximum(0.0, 1.30 - book["dscr"].to_numpy()) - 4.0 * np.minimum(noi_chg, 0.10))
    gap = book["refi_gap"].to_numpy()
    time = np.full(n, HORIZON_Q)
    event = np.zeros(n, dtype=int)
    for i in range(n):
        for q in range(1, HORIZON_Q + 1):
            if q == mat_q[i]:                    # at maturity: fails to refinance with probability rising in the gap
                logit = -3.2 + 7.0 * gap[i] + 0.5 * (base[i] + 6.2)
            else:
                logit = base[i] + ((0.3 + 2.5 * gap[i]) if q > mat_q[i] else 0.0)
            if rng.random() < 1 / (1 + np.exp(-logit)):
                event[i], time[i] = 1, q
                break
            if rng.random() < 0.02:
                time[i] = q
                break
    book["time_q"] = time
    book["event"] = event
    book["y_12m"] = ((event == 1) & (time <= 4)).astype(int)
    return book


def illustrative_loans(cfg: dict) -> pd.DataFrame:
    """Loan 1 is modeled on the example loan in Exhibit A-1, Section 3.2; Loans 2 and 3 are contrasting cases."""
    loans = pd.DataFrame([
        dict(loan="Loan 1 (office)", property_type="office", noi=1_650_000, cap_rate=0.080, balance=20_000_000,
             coupon=0.040, months_to_maturity=9, amort_years=0, occupancy=0.78, noi_chg_4q=-0.175,
             rate_chg_since_orig=0.025),
        dict(loan="Loan 2 (retail)", property_type="retail", noi=750_000, cap_rate=0.075, balance=7_500_000,
             coupon=0.050, months_to_maturity=20, amort_years=0, occupancy=0.88, noi_chg_4q=-0.03,
             rate_chg_since_orig=0.020),
        dict(loan="Loan 3 (multifamily)", property_type="multifamily", noi=600_000, cap_rate=0.060,
             balance=6_300_000, coupon=0.049, months_to_maturity=48, amort_years=0, occupancy=0.95,
             noi_chg_4q=0.03, rate_chg_since_orig=0.010),
    ])
    loans = add_refi_gap(loans, ust10=UST10, cfg=cfg)
    loans["ltv_current"] = loans["balance"] / (loans["noi"] / loans["cap_rate"])
    loans["dscr"] = loans["noi"] / (loans["balance"] * loans["coupon"])
    loans["debt_yield"] = loans["noi"] / loans["balance"]
    return loans


def band(pd_12m: float) -> str:
    return "High" if pd_12m >= HIGH else "Elevated" if pd_12m >= ELEVATED else "Standard"


def main() -> dict:
    rng = np.random.default_rng(SEED)
    cfg = load_underwriting()
    book = synthetic_book(rng, cfg)

    # Track A: monotone XGBoost, isotonic calibration on a held-out set
    idx = rng.permutation(len(book))
    fit_idx, cal_idx = idx[N_CAL:], idx[:N_CAL]
    X = book[FEATURES]
    model_a = fit_track_a(X.iloc[fit_idx], book["y_12m"].iloc[fit_idx], seed=SEED,
                          params={"n_estimators": 200, "min_child_weight": 20})
    cal = IsotonicCalibrator().fit(predict_raw(model_a, X.iloc[cal_idx]), book["y_12m"].iloc[cal_idx])

    # Track C: DeepSurv on standardized features, Breslow baseline
    mu, sd = X.mean(), X.std()
    Z = ((X - mu) / sd).to_numpy()
    model_c = fit_deepsurv(Z, book["time_q"].to_numpy(), book["event"].to_numpy(),
                           epochs=300, lr=3e-3, seed=SEED)
    lr_train = log_risk(model_c, Z)
    c_index = concordance_index(book["time_q"], book["event"], lr_train)
    times, H0 = breslow_baseline(lr_train, book["time_q"].to_numpy(), book["event"].to_numpy())

    loans = illustrative_loans(cfg)
    XL = loans[FEATURES]
    pd_a = cal.transform(predict_raw(model_a, XL))
    S = survival_curve(log_risk(model_c, ((XL - mu) / sd).to_numpy()), times, H0, np.arange(0, HORIZON_Q + 1))
    reasons = top_reasons(model_a, XL, k=3)

    records = []
    for i, row in loans.iterrows():
        b = band(float(pd_a[i]))
        records.append({
            "loan": row["loan"],
            "dscr": round(float(row["dscr"]), 2),
            "ltv_current": round(float(row["ltv_current"]), 2),
            "months_to_maturity": int(row["months_to_maturity"]),
            "refi_gap": round(float(row["refi_gap"]), 3),
            "pd_12m_track_a": round(float(pd_a[i]), 3),
            "cum_pd_1y_track_c": round(float(1 - S[i, 4]), 3),
            "cum_pd_3y_track_c": round(float(1 - S[i, 12]), 3),
            "cum_pd_5y_track_c": round(float(1 - S[i, 20]), 3),
            "risk_band": b,
            "reasons": reasons[i] if b != "Standard" else [],
            "survival_curve_track_c": [round(float(v), 4) for v in S[i]],
        })

    summary = {
        "seed": SEED, "n_loans": int(len(book)), "n_defaults_5y": int(book["event"].sum()),
        "n_defaults_12m": int(book["y_12m"].sum()), "n_calibration": N_CAL,
        "track_c_in_sample_c_index": round(float(c_index), 3),
        "band_cutoffs": {"High": HIGH, "Elevated": ELEVATED},
        "note": "Synthetic data only; output format, not evidence of predictive accuracy on real loans.",
        "loans": records,
    }
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "illustrative_outputs.json").write_text(json.dumps(summary, indent=2))
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        fig, ax = plt.subplots(figsize=(7, 3.6), dpi=150)
        for rec, color in zip(records, ["#b2402f", "#b7791f", "#2f6db5"]):
            ax.step(range(HORIZON_Q + 1), rec["survival_curve_track_c"], where="post", color=color, label=rec["loan"])
        ax.set_xlabel("Quarters from observation")
        ax.set_ylabel("S(t | x)")
        ax.set_ylim(0, 1.02)
        ax.set_xlim(0, HORIZON_Q)
        ax.grid(alpha=0.3)
        ax.legend(frameon=False, fontsize=8)
        ax.set_title("Track C survival curves (synthetic data; output format only)", fontsize=9)
        fig.tight_layout()
        fig.savefig(OUT / "survival_curves.png")
    except ImportError:
        pass
    return summary


if __name__ == "__main__":
    s = main()
    print(json.dumps({k: v for k, v in s.items() if k != "loans"}, indent=2))
    for r in s["loans"]:
        print(r["loan"], {k: r[k] for k in ["dscr", "ltv_current", "months_to_maturity", "refi_gap",
                                          "pd_12m_track_a", "cum_pd_1y_track_c", "cum_pd_3y_track_c",
                                          "cum_pd_5y_track_c", "risk_band"]})
        for x in r["reasons"]:
            print("   ", x)
