"""
CRE-DTS worked adoption demonstration for a SMALL lender on SYNTHETIC data (Tier 1, reference scoring).

Companion to adoption_demo.py. Shows the reduced-resource adoption path in Technical Design
Specification v1.10, Section 12.4:
  1. Map a small lender's core fields only (occupancy not held) to the data dictionary (Appendix A)
  2. Check whether the lender's own history is large enough for its own validation (Tier 2 floor)
  3. Tier 1: score with the unchanged reference model; set watch-level cut-offs from review capacity
  4. Benchmark check on the few defaults the lender has, against the rule-based screen

"Institution Y" and the reference pool are fictional; every number is generated by this script.
Nothing here is evidence of accuracy on real loans or of deployment at any institution.
Prepared September 2026, after the petition was filed.
"""
import json
import numpy as np
import pandas as pd
import xgboost as xgb
from sklearn.isotonic import IsotonicRegression

SEED = 2026
QUARTERS = pd.period_range("2013Q1", "2024Q4", freq="Q")
NQ = len(QUARTERS)
ust10 = np.interp(np.arange(NQ), [0, 12, 28, 36, 40, 44, 47],
                  [0.020, 0.023, 0.015, 0.016, 0.035, 0.043, 0.042])
TYPES = ["Office", "Multifamily", "Retail", "Industrial"]
SPREAD = {"Office": 0.022, "Multifamily": 0.017, "Retail": 0.023, "Industrial": 0.019}
CAP0 = {"Office": 0.065, "Multifamily": 0.055, "Retail": 0.068, "Industrial": 0.060}
LIMITS = {"Office": (1.35, 0.60, 0.10), "Multifamily": (1.25, 0.70, 0.08),
          "Retail": (1.35, 0.65, 0.095), "Industrial": (1.30, 0.65, 0.09)}
TIER2_MIN_DEFAULTS = 30   # indicative floor (Spec 12.4); to be set during Phase 2 validation


def type_trend(ptype, i):
    if ptype == "Office":
        return 0.004 if i < 29 else -0.018
    if ptype == "Retail":
        return -0.002 if i < 28 else 0.001
    return 0.006


def debt_constant(r, years=30):
    m = r / 12
    return 12 * m / (1 - (1 + m) ** (-12 * years))


def simulate(n, rng, mix, size_mu, terms, prefix, ltv=(0.50, 0.76)):
    rows = []
    for loan in range(n):
        ptype = rng.choice(TYPES, p=mix)
        o = int(rng.integers(0, 40))
        mat = o + int(rng.choice(terms))
        io = rng.random() < 0.45
        val0 = float(np.exp(rng.normal(np.log(size_mu), 0.6)))
        bal = val0 * float(rng.uniform(*ltv))
        noi = val0 * (CAP0[ptype] + rng.normal(0, 0.004))
        coupon = ust10[o] + SPREAD[ptype] + rng.normal(0, 0.003)
        ds = bal * (coupon if io else debt_constant(coupon))
        occ = float(np.clip(rng.normal(0.93, 0.04), 0.7, 1.0))
        shock = rng.normal(0, 0.006)
        hn, ho, hd = [], [], []
        for i in range(o, min(mat + 1, NQ)):
            if i > o:
                g = type_trend(ptype, i) + shock + rng.normal(0, 0.02)
                noi *= np.exp(g)
                occ = float(np.clip(occ + 0.6 * g + rng.normal(0, 0.006), 0.35, 1.0))
                if not io:
                    bal *= 0.995
            cap_t = CAP0[ptype] + 0.55 * (ust10[i] - ust10[0]) + (0.008 if (ptype == "Office" and i >= 30) else 0)
            value = noi / cap_t
            dscr = noi / ds
            hn.append(noi); ho.append(occ); hd.append(dscr)
            dmin, lmax, dymin = LIMITS[ptype]
            L = min(noi / (dmin * debt_constant(ust10[i] + SPREAD[ptype])), lmax * noi / cap_t, noi / dymin)
            gap = max(0.0, bal - L) / bal
            rows.append(dict(loan=f"{prefix}-{loan:04d}", q=i, ptype=ptype, orig_q=o, mat_q=mat, balance=bal,
                             noi=noi, value=value, occ=occ, debt_service=ds, mtm=(mat - i) * 3, refi_gap=gap,
                             noi_4q=hn[-5] if len(hn) >= 5 else np.nan, occ_4q=ho[-5] if len(ho) >= 5 else np.nan,
                             dscr_4q=hd[-5] if len(hd) >= 5 else np.nan, event=""))
            noi_chg = (noi / hn[-5] - 1) if len(hn) >= 5 else 0.0
            logit = (-6.2 + 2.2 * max(0, 1.15 - dscr) + 2.5 * max(0, bal / value - 0.75)
                     - 3.0 * min(noi_chg, 0.1) + 1.2 * gap)
            if i == mat:
                p_mat = 1 / (1 + np.exp(-(-3.2 + 9.0 * gap)))
                rows[-1]["event"] = "maturity_default" if rng.random() < p_mat else "payoff"
                break
            if rng.random() < 1 / (1 + np.exp(-logit)):
                rows[-1]["event"] = "term_default"
                break
    return pd.DataFrame(rows)


def features(panel):
    df = panel.copy()
    df["obs_q"] = df["q"] + 1
    df["ltv_current"] = df["balance"] / df["value"]
    df["dscr"] = df["noi"] / df["debt_service"]
    df["debt_yield"] = df["noi"] / df["balance"]
    df["noi_chg_4q"] = df["noi"] / df["noi_4q"] - 1
    df["occ_chg_4q"] = df["occ"] - df["occ_4q"]
    df["dscr_chg_4q"] = df["dscr"] - df["dscr_4q"]
    df["mtm_obs"] = df["mtm"] - 3
    df["rate_chg_since_orig"] = [ust10[q] - ust10[o] for q, o in zip(df["q"], df["orig_q"])]
    for t in TYPES:
        df["pt_" + t] = (df["ptype"] == t).astype(int)
    ev = panel[panel["event"].str.contains("default")][["loan", "q", "event"]].rename(columns={"q": "def_q", "event": "def_type"})
    df = df.merge(ev, on="loan", how="left")
    df["y_12m"] = ((df["def_q"] >= df["obs_q"] - 1) & (df["def_q"] <= df["obs_q"] + 2)).astype(int)
    df = df[df["event"] == ""].copy()
    df["obs_year"] = [(QUARTERS[0] + min(i, NQ - 1)).year for i in df["obs_q"]]
    return df


FEATS = ["ltv_current", "dscr", "debt_yield", "occ", "refi_gap", "mtm_obs", "noi_chg_4q",
         "occ_chg_4q", "dscr_chg_4q", "rate_chg_since_orig"] + ["pt_" + t for t in TYPES]
MONO = {"ltv_current": 1, "refi_gap": 1, "dscr": -1, "debt_yield": -1, "occ": -1}

# ------------------------------------------------ reference model (stands in for the public-data baseline, Spec 4.1)
rng_ref = np.random.default_rng(SEED + 1)
ref = features(simulate(4000, rng_ref, [0.3, 0.3, 0.2, 0.2], 12e6, [20, 28, 40], "REF"))
drop = rng_ref.random(len(ref)) < 0.35          # occupancy treated as optional in the reference data
ref.loc[drop, ["occ", "occ_chg_4q"]] = np.nan
tr = ref[(ref.obs_year >= 2014) & (ref.obs_year <= 2018)]
ca = ref[(ref.obs_year >= 2019) & (ref.obs_year <= 2020)]
model = xgb.XGBClassifier(n_estimators=300, max_depth=3, learning_rate=0.05, subsample=0.8, colsample_bytree=0.8,
                          min_child_weight=5, random_state=SEED,
                          monotone_constraints=tuple(MONO.get(f, 0) for f in FEATS),
                          scale_pos_weight=float((tr.y_12m == 0).sum() / max(1, (tr.y_12m == 1).sum())))
model.fit(tr[FEATS], tr["y_12m"])
iso = IsotonicRegression(out_of_bounds="clip").fit(model.predict_proba(ca[FEATS])[:, 1], ca["y_12m"])
pd_of = lambda X: iso.predict(model.predict_proba(X[FEATS])[:, 1])

# ------------------------------------------------ Institution Y: small community lender
rng_y = np.random.default_rng(SEED + 2)
ypanel = simulate(180, rng_y, [0.15, 0.35, 0.30, 0.20], 2.5e6, [12, 20, 28], "IY", ltv=(0.45, 0.68))
CORE = [("Loan_ID", "loan_id"), ("Prop_Type", "property_type"), ("Stmt_Date", "reporting_period_end"),
        ("Rcvd_Date", "available_date"), ("Principal_Bal", "balance"), ("NOI_Annual", "noi"),
        ("Debt_Service_Annual", "debt_service"), ("Collateral_Value", "value_current"), ("Maturity", "maturity_date")]
NOT_HELD_Y = ["occupancy", "watchlist_flag", "borrower_strength"]
y = features(ypanel)
y[["occ", "occ_chg_4q"]] = np.nan              # Institution Y does not track occupancy
y["pd"] = pd_of(y)

hist = y[(y.obs_year >= 2014) & (y.obs_year <= 2023)]
n_def_hist = int(ypanel[(ypanel.event.str.contains("default")) & (ypanel.q <= NQ - 5)].shape[0])
tier2_ok = n_def_hist >= TIER2_MIN_DEFAULTS

# Tier 1 cut-offs from review capacity on the current book (no historical calibration needed)
current = y[y.q == NQ - 1].copy()
CAP = {"Watch": 0.20, "Elevated": 0.08, "High": 0.03}   # share of the current book the lender can review at each level
TH = {lvl: float(np.quantile(current["pd"], 1 - s)) for lvl, s in CAP.items()}
lvl = lambda p: np.where(p >= TH["High"], "High", np.where(p >= TH["Elevated"], "Elevated",
                         np.where(p >= TH["Watch"], "Watch", "Standard")))
current["level"] = lvl(current["pd"])
counts = current["level"].value_counts().reindex(["High", "Elevated", "Watch", "Standard"]).fillna(0).astype(int).to_dict()

# Benchmark check on the lender's own few defaults (2022Q2-2024Q4): flagged Watch-or-higher >= 6 months ahead?
tq0 = QUARTERS.get_loc(pd.Period("2022Q1"))
rule_rate = float(((current.dscr < 1.0) | (current.ltv_current > 0.80)).mean())
TH_EQ = float(np.quantile(current["pd"], 1 - rule_rate))   # model cut-off flagging the same share of the book as the rule
bench = []
for loan, g in y[y.def_q.notna()].groupby("loan"):
    dq = int(g.def_q.iloc[0])
    if dq < tq0 + 1 or dq >= NQ:
        continue
    w = g[(g.obs_q >= tq0) & (g.obs_q <= dq)]
    f_model = w[w.pd >= TH_EQ]
    f_rule = w[(w.dscr < 1.0) | (w.ltv_current > 0.80)]
    lead = lambda f: (dq + 1 - int(f.obs_q.min())) * 3 if len(f) else None
    bench.append(dict(loan=loan, type=g.def_type.iloc[0], model_lead=lead(f_model), rule_lead=lead(f_rule)))
bench = pd.DataFrame(bench)
n_b = len(bench)
model6 = int((bench.model_lead >= 6).sum()) if n_b else 0
rule6 = int((bench.rule_lead >= 6).sum()) if n_b else 0

out = dict(seed=SEED, n_ref_loans=4000, n_loans=180, n_current=int(len(current)),
           core_fields=[dict(source=s, target=t) for s, t in CORE], not_held=NOT_HELD_Y,
           n_defaults_history=n_def_hist, tier2_min_defaults=TIER2_MIN_DEFAULTS, tier2_ok=bool(tier2_ok),
           capacity=CAP, thresholds=TH, watchlist_counts=counts,
           bench=dict(n=n_b, model_ge6=model6, rule_ge6=rule6,
                      rule_flag_rate_current=rule_rate, model_cutoff_same_rate=TH_EQ))
from pathlib import Path
_out = Path(__file__).resolve().parent / "out"
_out.mkdir(exist_ok=True)
json.dump(out, open(_out / "small_lender_demo_results.json", "w"), indent=2, default=str)
print(json.dumps(out, indent=2, default=str))
